src/order/urls.py
from django.conf import settings
from django.urls import path, include
from . import views

urlpatterns = [
    path('new/', views.new_order, name='order-new'),
]

src/wxservice/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('verify', views.WxServiceView.as_view(), name='verify'),
    # path('verify', views.wxverify, name='verify'),
    # path('order/', views.new_order, name='new-order'),
    path('login/', views.login_page, name='wx-login'),
]

src/youswebsite/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth import views as auth_views
from review import views
from user import views as user_views

urlpatterns = [
    path('', views.index, name='home'),
    path('review/', include('review.urls')),
    path('order/', include('order.urls')),
    path('wx/', include('wxservice.urls')),
    path('profile/', user_views.profile, name='profile'),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logout.html'), name='logout'),
    path('admin/', admin.site.urls),
    # path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/order/models.py
from django.db import models
from django.conf import settings
from datetime import datetime


class Order(models.Model):
    '''
    Customer Order Model tabel
    This Model define how our customer order our product,
    every customer have a unique user account in our db
    we can use the foreign key relationship to connect this
    two table, once our user order a product from our store,
    we can immediatly give a record to ther user account.

    :field  user            each user can have many orders
    :field  customer        customer who issue a order
    :field  contact_phone   customer's phone
    :field  address         customer's recieve address
    :field  status          track the order's status for message parser
    :field  product         user's order type outline
    :field  description     user's personal description for product
    :field  create_time     order's created time
    :field  finish_time     order's finishe time
    '''
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    customer = models.CharField(
        max_length=200,
        verbose_name="联系人",
        help_text='请务必仔细填写填，方便我们联系你。'
    )
    contact_phone = models.CharField(
        '联系电话',
        max_length=11,
        help_text='请务必填写正确！ 填写11位的电话号码。',
    )
    address = models.CharField(
        '送货地址',
        max_length=200,
        help_text='请务必填写正确！ 方便我们给你送货。',
        default=''
    )
    PRODUCT_CHOICES = (
        ('广告', (
            ('ad1', '喷绘'),
            ('ad2', '写真'),
        )),
        ('打印', (
            ('pt1', '论文修改'),
            ('pt2', '复习资料'),
        )),
        ('other', '其他'),
    )
    product = models.CharField(
        verbose_name='产品规格',
        max_length=10,
        choices=PRODUCT_CHOICES,
        default='ad1'
    )
    description = models.TextField(
        verbose_name='具体要求请备注',
        blank=True,
        null=True,
        help_text='请添加你对产品设计制作和安装过程中的详细要求。',
    )

    STATUS_CHOICE = (
        (0, '等待处理'),
        (1, '前台已经接单'),
        (2, '设计师设计中...'),
        (3, '等待定稿...'),
        (4, '等待安装...'),
        (5, '正在配送安装...'),
        (6, '订单完成'),
    )
    status = models.IntegerField(
        verbose_name='产品状态',
        default=0,
        choices=STATUS_CHOICE,
    )
    # price = models.FloatField(default=0.0)
    create_time = models.DateTimeField(
        verbose_name='订单生成时间',
        default=datetime.now(),
    )
    # finish_time = models.DateTimeField(
    #     verbose_name='订单完成时间',
    #     auto_now=True
    # )
    finish_time = models.DateTimeField(
        verbose_name='订单完成时间',
        auto_now=True
    )

    def contact_phone_format(self):
        return f'{self.contact_phone[:3]}-{self.contact_phone[3:7]}-{self.contact_phone[7:12]}'

    contact_phone_format.admin_order_field = 'finish_time'
    # contact_phone_format.boolean = True
    contact_phone_format.short_description = '联系方式'

    def finish_time_check(self):
        if self.status == 6:
            self.finish_time = datetime.now()
            return self.finish_time
        else:
            return '-'

    # def front_review(self):
    #     return self.review_set.filter(stuff__position=1).first().stars

    # def designer_review(self):
    #     return self.review_set.filter(stuff__position=2).first().stars

    # def installer_review(self):
    #     return self.review_set.filter(stuff__position=3).first().stars

    def __str__(self):
        return self.customer

src/wxservice/models.py
from django.db import models

src/wxservice/forms.py
from django import forms

src/wxservice/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.urls import reverse
from django.views.generic import View

from wechatpy.utils import check_signature
from wechatpy.exceptions import InvalidSignatureException
from wechatpy import parse_message
from wechatpy.messages import TextMessage
from wechatpy.replies import TextReply, ImageReply, VoiceReply, VideoReply, ArticlesReply, EmptyReply

from . import clients  # Wechat API client
from user.models import User
from django.contrib.auth import login, authenticate


class WxServiceView(View):
    _WEIXIN_TOKEN = 'verify'

    def get(self, request):
        # redirect_uri = f'http://{request.get_host()}{reverse("wx-login")}'
        # client = clients.create_menu(redirect_uri)
        signature = request.GET.get("signature", None)
        timestamp = request.GET.get("timestamp", None)
        nonce = request.GET.get("nonce", None)
        echostr = request.GET.get("echostr", None)
        token = self._WEIXIN_TOKEN
        try:
            check_signature(token, signature, timestamp, nonce)
            return HttpResponse(echostr)
        except InvalidSignatureException:
            return HttpResponse('Invalid Signature Exception')

    @csrf_exempt
    def post(self, request):
        xml = request.body
        msg = parse_message(xml)
        if msg.type == 'text':
            # 获取文本内容
            try:
                content = msg.content
                # print(res)
                # print(json.dump(res))
                reply = TextReply(content=content, message=msg)
                r_xml = reply.render()
                # 获取唯一标记用户的openid，下文介绍获取用户信息会用到
                openid = msg.source
                # print(openid)
                return HttpResponse(r_xml)
            except Exception as e:
                # 自行处理
                return HttpResponse('success')
            # return HttpResponse('')
        elif msg.type == 'image':
            print(msg.image, msg.media_id)
            reply = ArticlesReply(message=msg)

            reply.add_article({
                'title': 'Welcome tom my channel!',
                'description': 'Finally, we meet you here,\nYou must know you are very important for us!',
                'image': msg.image,
                'url': 'https://baidu.com'
            })
            r_xml = reply.render()
            return HttpResponse(r_xml)
        elif msg.type == 'voice':
            print(msg.format, msg.recognition)
            reply = VoiceReply(media_id=msg.media_id, message=msg)
            return HttpResponse(reply.render())
        elif msg.type == 'video':
            print(msg)
            print(msg.media_id, msg.thumb_media_id)
            reply = VideoReply(media_id=msg.media_id, title='Test video', description='Description', message=msg)

            return HttpResponse(reply.render())
        elif msg.type == 'location':
            print(msg.location_x, msg.location_y, msg.scale, msg.label, msg.location)
            return HttpResponse('Success')

        elif msg.type == 'event':
            # print(msg.type)
            if msg.event == 'subscribe':
                try:
                    reply = TextReply(content='Welcome to my channel', message=msg)
                    r_xml = reply.render()
                    return HttpResponse(r_xml)
                except:
                    return HttpResponse('Success')
            elif msg.event == 'unsubscribe':
                try:
                    reply = TextReply(content='See you again!', message=msg)
                    r_xml = reply.render()
                    return HttpResponse(r_xml)
                except:
                    return HttpResponse('Success')
            elif msg.event == 'subscribe_scan':
                try:
                    print(msg.scene_id, msg.ticket)
                    reply = TextReply(content='See you again!', message=msg)
                    r_xml = reply.render()
                    return HttpResponse(r_xml)
                except:
                    return HttpResponse('Success')
            elif msg.event == 'scan':
                try:
                    print(msg.scene_id, msg.ticket)
                    reply = TextReply(content='See you again!', message=msg)
                    r_xml = reply.render()
                    return HttpResponse(r_xml)
                except:
                    return HttpResponse('Success')
            elif msg.event == 'location':
                try:
                    print(msg.latitude, msg.longitude, msg.precision)
                    reply = TextReply(content='See you again!', message=msg)
                    r_xml = reply.render()
                    return HttpResponse(r_xml)
                except:
                    return HttpResponse('Success')
            elif msg.event == 'click':
                try:
                    print(msg.key)
                    reply = TextReply(content=msg.key, message=msg)
                    r_xml = reply.render()
                    return HttpResponse(r_xml)
                except:
                    return HttpResponse('Success')
            elif msg.event == 'view':
                try:
                    print(f'{msg.url}\n=========')
                    reply = TextReply(content=msg.url, message=msg)
                    r_xml = reply.render()
                    return HttpResponse(r_xml)
                except:
                    return HttpResponse('Success')


def login_page(request):
    if request.method == "GET" and request.GET.get("code") and not request.user.is_authenticated:
        """
        Create a new user if the user doesn't exist
        when the user in our database, just login the user
        """
        redirect_uri = f'http://{request.get_host()}{reverse("wx-login")}'
        client = clients.web_authorize(redirect_uri)

        code = request.GET.get("code", None)
        res = client.fetch_access_token(code)
        res = client.get_user_info()

        openid = res['openid']
        nickname = res['nickname']
        headimgurl = res['headimgurl']
        user = authenticate(request=request, openid=openid, nickname=nickname, headimgurl=headimgurl)

        if user is not None:
            login(request, user)
        else:
            print('You do not have permission to do this!')
            return redirect('login')
    context = {}
    return render(request, 'wxservice/profile.html', context=context)

src/wxservice/templates/wxservice/_nav.html
<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
        aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'home' %}">
        <img height="45" width="45" src="{% if user.profile.image.url %}{{ user.profile.image.url }}{% else%}{{ user.headimgurl}} {%endif%}"
            alt="" class="rounded-circle account-img">
    </a>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <div class="navbar-nav">
            {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'order-new' %}">新订单</a>
            <a class="nav-link" href="{% url 'wx-login' %}">我的评价</a>
            <a class="nav-link" href="{% url 'wx-login' %}">个人信息</a>
            {% else %}
            <a class="nav-link" href="{% url 'login' %}">登录</a>
            <a class="nav-link" href="{% url 'register' %}">注册</a>
            {% endif %}
        </div>
        <!-- <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="text" placeholder="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form> -->
    </div>
</nav>

src/wxservice/templates/wxservice/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> -->
  <link rel="stylesheet" type="text/css" href="{% static 'collectstar/css/bootstrap.min.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'collectstar/css/style.css' %}" />
  {% block customCss %}

  {% endblock %}
  <title>种树人-</title>
</head>

<body>
  <div class="container">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
    {% endfor %}
    {% endif %}
    {% include 'wxservice/_nav.html' %}
    {% block content%}

    {% endblock %}
  </div>
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="{% static 'collectstar/js/jquery-3.1.1.slim.min.js' %}" crossorigin="anonymous"></script>
  <script src="{% static 'collectstar/js/tether.min.js' %}" crossorigin="anonymous"></script>
  <script src="{% static 'collectstar/js/ie10-viewport-bug-workaround.js' %}" crossorigin="anonymous"></script>
  <script src="{% static 'collectstar/js/bootstrap.min.js' %}" crossorigin="anonymous"></script>
  <script src="{% static 'collectstar/js/main.js' %}" crossorigin="anonymous"></script>
  {% block javascript %}
  {% endblock %}
</body>

</html>

src/wxservice/templates/wxservice/new-order.html
{% extends 'wxservice/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block customCss %}
<!-- <link rel="stylesheet" type="text/css" href="{% static 'collectstar/css/jd.global.min.css' %}"/> -->
<!-- <link rel="stylesheet" type="text/css" href="{% static 'collectstar/css/jd.comment.min.css' %}"/> -->
{% endblock %}

{% block content%}
<div class="jumbotron">
    <div class="container">
        <h1 class="display-3">{{title}}</h1>
        {% if confirm_message %}
        <p>{{ confirm_message }}</p>
        {% endif %}

        {% if form %}
        <form action="" method="post">
            {% csrf_token %}
            {{ form |crispy }}
            <input type="submit" value="Submit" class="btn btn-primary">
        </form>
        {% endif %}
    </div>
</div>

{% endblock %}

{% block javascript %}
<script>
</script>
{% endblock %}

src/wxservice/templates/wxservice/profile.html
{% extends 'wxservice/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content%}

<!-- <div class="media">
    <img height="72" width="72" src="{% if user.profile.image.url %}{{ user.profile.image.url }}{% else%}{{ user.headimgurl}} {%endif%}"
        alt="" class="rounded-circle account-img">
    <div class="media-body pl-4">
        {% if user.username %}
        <h2 class="account-heading">{{ user.username}}</h2>
        {% else %}
        <h2 class="account-heading">{{ user.nickname}}</h2>
        {% endif %}
        <p class="text-secondary">{{ user.email }}</p>
    </div>
</div> -->
<!-- Order information Right here -->
<div class="card-header">
    <h5 class="my-0 mb-3 font-weight-normal">Your Orders</h5>
    {% for order in user.order_set.all %}
    <div class="card flex-row mb-4 shadow-sm">
        <img class="card-img-right mr-2" data-src="holder.js/80x80?theme=thumb" alt="Thumbnail [200x250]" style="width: 100px; height: 100px;"
            src="data:image/svg+xml;charset=UTF-8,%3Csvg%20width%3D%22200%22%20height%3D%22250%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20200%20250%22%20preserveAspectRatio%3D%22none%22%3E%3Cdefs%3E%3Cstyle%20type%3D%22text%2Fcss%22%3E%23holder_166d2d5ad9d%20text%20%7B%20fill%3A%23eceeef%3Bfont-weight%3Abold%3Bfont-family%3AArial%2C%20Helvetica%2C%20Open%20Sans%2C%20sans-serif%2C%20monospace%3Bfont-size%3A13pt%20%7D%20%3C%2Fstyle%3E%3C%2Fdefs%3E%3Cg%20id%3D%22holder_166d2d5ad9d%22%3E%3Crect%20width%3D%22200%22%20height%3D%22250%22%20fill%3D%22%2355595c%22%3E%3C%2Frect%3E%3Cg%3E%3Ctext%20x%3D%2256.203125%22%20y%3D%22130.7%22%3EThumbnail%3C%2Ftext%3E%3C%2Fg%3E%3C%2Fg%3E%3C%2Fsvg%3E"
            data-holder-rendered="true">
        <div class="card-body flex-column align-items-start">
            <h5 class="mb-0">
                <a class="text-dark" href="#">{{order.customer}}</a>
            </h5>
            <div class="mb-0 text-muted">{{ order.create_time }}</div>
            <p class="card-text mb-0">{{ order.order_detail }}</p>
            <a class="" href="#">Review</a>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}