src/order/urls.py
from django.conf import settings
from django.urls import path, include
from . import views

urlpatterns = [
    path('new/', views.new_order, name='order-new'),
]

src/review/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:order_id>', views.review, name='review'),
]

src/youswebsite/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth import views as auth_views
from review import views
from user import views as user_views

urlpatterns = [
    path('', views.index, name='home'),
    path('review/', include('review.urls')),
    path('order/', include('order.urls')),
    path('wx/', include('wxservice.urls')),
    path('profile/', user_views.profile, name='profile'),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='user/logout.html'), name='logout'),
    path('admin/', admin.site.urls),
    # path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/review/models.py
from django.db import models
from order.models import Order
from user.models import Stuff


class Review(models.Model):
    STARS_CHOCIES = (
        (1, 'One Star'),
        (2, 'Two Stars'),
        (3, 'Three Stars'),
        (4, 'Four Stars'),
        (5, 'Five Sarts'),
    )
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    stuff = models.ForeignKey(Stuff, on_delete=models.CASCADE)
    stars = models.IntegerField(choices=STARS_CHOCIES, default=0)
    comment = models.TextField(blank=True)

    def __str__(self):
        return f'{self.order.customer}-{self.stuff.position}-{self.stars}'

src/review/forms.py
from django import forms
from django.forms import ModelForm
from django.forms import inlineformset_factory
from .models import Review


class ReviewForm(forms.Form):
    # customer_name = forms.CharField(required=True, max_length=200, help_text='请输入你的客户名称', label='客户名称')
    # phone = forms.CharField(required=True, max_length=11, label='联系方式')
    # comment = forms.CharField(widget=forms.Textarea, label='更多建议')
    STARS_CHOCIES = (
        (1, 'One Star'),
        (2, 'Two Stars'),
        (3, 'Three Stars'),
        (4, 'Four Stars'),
        (5, 'Five Sarts'),
        (6, 'Five Sarts'),
        (7, 'Five Sarts'),
        (8, 'Five Sarts'),
        (9, 'Five Sarts'),
    )
    # front stuff review
    ft_star = forms.ChoiceField(choices=STARS_CHOCIES, label="前台服务评分")
    # designer review
    ds_star = forms.ChoiceField(choices=STARS_CHOCIES, label="设计服务评分")
    # transfor review
    tf_star = forms.ChoiceField(choices=STARS_CHOCIES, label="配送服务评分")

    # start = forms.ChoiceField()

    # comment

src/review/views.py
# -*- coding: utf-8 -*-
"""
views.py
@author wilton
@version 2018-10-30
"""
from django.shortcuts import render, get_object_or_404, redirect
from .forms import ReviewForm
# from django.forms import inlineformset_factory
from .models import Review
from order.models import Order
from django.contrib.auth.decorators import login_required


def index(request):
    context = {}
    return render(request, 'review/index.html', context=context)


@login_required
def review(request, order_id=None):
    order = get_object_or_404(Order, pk=order_id, user=request.user)
    review_sets = order.review_set.all()

    if not review_sets.exists():
        return redirect('index')

    title = '请对我们做出评价'
    product = f'Please review: {order.customer}'
    # CollectStarFormSet = inlineformset_factory(Order, Star, fields=('stars',))
    data = {
        ''
    }
    form = ReviewForm(request.POST or None)
    confirm_message = ''
    if form.is_valid():
        ft_star = form.cleaned_data['ft_star']
        ds_star = form.cleaned_data['ds_star']
        tf_star = form.cleaned_data['tf_star']
        # comment = form.cleaned_data['comment']
        review_sets = order.review_set.all()
        for review in review_sets:
            if review.stuff.position == 1:
                review.stars = ft_star
            elif review.stuff.position == 2:
                review.stars = ds_star
            elif review.stuff.position == 3:
                review.stars = tf_star
            review.save()
        print(review_sets)
        ft_review = Review()
        # save to our database
        # print(order, star, comment)
        title = 'Thanks!'
        confirm_message = 'You have a chance to get bouns.'
        form = None

        print(request.POST)
    context = {'title': title, 'product': product, 'review_sets': review_sets,
               'form': form, 'confirm_message': confirm_message, }
    # print(dir(request))
    return render(request, 'review/star.html', context=context)

src/review/templates/review/_navbar.html
<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault"
        aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'home' %}">TREE BY</a>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            {% url 'home' as home%}
            {% url 'review' as review%}
            <li class="nav-item {% if request.path == home%} active {% endif %}">
                <a class="nav-link" href="{% url 'home'%}">首页 <span class="sr-only">(current)</span></a>
            </li>

            <!-- <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
        </li> -->
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">服务</a>
                <div class="dropdown-menu" aria-labelledby="dropdown01">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" href="#">Something else here</a>
                </div>
            </li>
        </ul>
        <div class="navbar-nav">
            {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'profile' %}">个人信息</a>
            <a class="nav-link" href="{% url 'logout' %}">注销</a>
            {% else %}
            <a class="nav-link" href="{% url 'login' %}">登录</a>
            <a class="nav-link" href="{% url 'register' %}">注册</a>
            {% endif %}
        </div>
        <!-- <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> -->
    </div>
</nav>

src/review/templates/review/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous"> -->
  <link rel="stylesheet" type="text/css" href="{% static 'review/css/bootstrap.min.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'review/css/style.css' %}" />
  {% block customCss %}

  {% endblock %}
  <title>种树人-</title>
</head>

<body>
  {% include 'review/_navbar.html' %}
  <div class="container">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">{{ message }}</div>
    {% endfor %}
    {% endif %}
    {% block content%}

    {% endblock %}
  </div>
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="{% static 'review/js/jquery-3.1.1.slim.min.js' %}" crossorigin="anonymous"></script>
  <script src="{% static 'review/js/tether.min.js' %}" crossorigin="anonymous"></script>
  <script src="{% static 'review/js/ie10-viewport-bug-workaround.js' %}" crossorigin="anonymous"></script>
  <script src="{% static 'review/js/bootstrap.min.js' %}" crossorigin="anonymous"></script>
  <script src="{% static 'review/js/main.js' %}" crossorigin="anonymous"></script>
  {% block javascript %}
  {% endblock %}
</body>

</html>

src/review/templates/review/index.html
{% extends 'review/base.html' %}

{% block content%}
<div class="jumbotron">
    <div class="container">
        <h1 class="display-3">Hello Tree By</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called a
            jumbotron and three supporting pieces of content. Use it as a starting point to create something more
            unique.</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
    </div>
</div>
{% endblock %}

src/review/templates/review/star.html
{% extends 'review/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block customCss %}
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
<link rel="stylesheet" href="{% static 'review/css/fontawesome-stars.css' %}">
{% endblock %}

{% block content%}
<div class="jumbotron">
    <div class="container">
        <h1 class="display-3">{{title}}</h1>
        <p class="display-5">{{product}}</p>
        {% if confirm_message %}
        <p>{{ confirm_message }}</p>
        {% endif %}

        {% if form %}
        <form action="" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="{{ form.ft_star.id_for_label }}">{{form.ft_star.label}}</label>
                {{ form.ft_star }}
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
            </div>

            <div class="form-group">
                <label for="{{ form.ds_star.id_for_label }}">{{form.ds_star.label}}</label>
                {{ form.ds_star }}
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
            </div>

            <div class="form-group">
                <label for="{{ form.tf_star.id_for_label }}">{{form.tf_star.label}}</label>
                {{ form.tf_star }}
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
            </div>
            <input type="submit" value="review" class="btn btn-primary">
        </form>
        {% endif %}
    </div>
</div>

{% for review in review_sets %}
<img src="{{ review.stuff.user.profile.image.url }}" alt="" height="50">
{% endfor %}
{% endblock %}

{% block javascript %}
<script src="{% static 'review/js/jquery.barrating.min.js' %}"></script>
<script type="text/javascript">
    $(function () {
        $('#id_ds_star').barrating({
            theme: 'fontawesome-stars',
            showSelectedRating: true
        });
        $('#id_ft_star').barrating({
            theme: 'fontawesome-stars'
        });
        $('#id_tf_star').barrating({
            theme: 'fontawesome-stars'
        });
    });
</script>

{% endblock %}